# Generated by Django 3.0 on 2021-09-15 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(choices=[('RB', 'Russian Blue'), ('PC', 'Persian Cat'), ('RD', 'Ragdoll'), ('SC', 'Sphynx Cat'), ('BC', 'Belgal Cat'), ('BM', 'Birman'), ('SC', 'Siberian Cat'), ('BC', 'Bombay Cat'), ('K', 'Korat'), ('TC', 'Thai Cat')], default='RB', max_length=2)),
                ('bio', models.TextField(max_length=200)),
                ('images', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
