# Generated by Django 3.0 on 2021-09-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
