# Generated by Django 3.0 on 2021-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
