# Generated by Django 3.0 on 2021-09-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210920_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
    ]
