# Generated by Django 3.0 on 2021-09-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210920_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='age',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='name',
        ),
    ]
