# Generated by Django 3.0 on 2021-09-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210920_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
