# Generated by Django 3.0 on 2021-09-21 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210921_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
